/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prg03aurorarodriguesmaciel.br.com.ifba.view;

/**
 *
 * @author auror
 */
public class calculadora_idade extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(calculadora_idade.class.getName());

    /**
     * Creates new form calculadora_idade
     */
    public calculadora_idade() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAno = new javax.swing.JLabel();
        spnAno = new javax.swing.JSpinner();
        btnCalcular = new javax.swing.JToggleButton();
        lblIdade = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblAno.setText("Ano de nascimento:");
        getContentPane().add(lblAno);
        lblAno.setBounds(78, 38, 105, 16);

        spnAno.setModel(new javax.swing.SpinnerNumberModel(1989, 1900, 2026, 1));
        getContentPane().add(spnAno);
        spnAno.setBounds(222, 32, 89, 22);

        btnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prg03aurorarodriguesmaciel/br/com/ifba/image/calculadora.png"))); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(this::btnCalcularActionPerformed);
        getContentPane().add(btnCalcular);
        btnCalcular.setBounds(134, 146, 108, 39);

        lblIdade.setText("Idade:");
        getContentPane().add(lblIdade);
        lblIdade.setBounds(78, 210, 37, 16);

        lblResultado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblResultado.setForeground(new java.awt.Color(255, 0, 0));
        lblResultado.setText("0");
        getContentPane().add(lblResultado);
        lblResultado.setBounds(152, 203, 37, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prg03aurorarodriguesmaciel/br/com/ifba/image/pessoa.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(274, 117, 76, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        int ano = (int) spnAno.getValue();//Pega o valor do JSpinner, converte de objeto para inteiro e adiciona em ano
        int idade = (2026 - ano);//Calcula a idade a partir do ano atual e ano de nascimento
        lblResultado.setText(String.valueOf(idade));//Converte o inteiro idade em string e mostra em lblResultado                                        
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new calculadora_idade().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAno;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JSpinner spnAno;
    // End of variables declaration//GEN-END:variables
}
