/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prg03aurorarodriguesmaciel.br.com.ifba.atividade08.view;

/**
 *
 * @author auror
 */
public class TelaPagamento extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPagamento.class.getName());

    /**
     * Creates new form TelaPagamento
     */
    public TelaPagamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblValor = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        lblPagamento = new javax.swing.JLabel();
        btnDinheiro = new javax.swing.JButton();
        btnCartao = new javax.swing.JButton();
        btnPix = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblValor.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblValor.setText("Valor da compra:");

        txtValor.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N

        lblPagamento.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblPagamento.setText("Forma de pagamento:");

        btnDinheiro.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnDinheiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prg03aurorarodriguesmaciel/br/com/ifba/atividade08/image/dinheiro.png"))); // NOI18N
        btnDinheiro.setText("Dinheiro");
        btnDinheiro.addActionListener(this::btnDinheiroActionPerformed);

        btnCartao.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnCartao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prg03aurorarodriguesmaciel/br/com/ifba/atividade08/image/cartao.png"))); // NOI18N
        btnCartao.setText("Cartão");
        btnCartao.addActionListener(this::btnCartaoActionPerformed);

        btnPix.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnPix.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prg03aurorarodriguesmaciel/br/com/ifba/atividade08/image/pix.png"))); // NOI18N
        btnPix.setText("Pix");
        btnPix.addActionListener(this::btnPixActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(btnDinheiro)
                .addGap(40, 40, 40)
                .addComponent(btnCartao)
                .addGap(32, 32, 32)
                .addComponent(btnPix)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPagamento)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblValor, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValor)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(lblPagamento)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDinheiro)
                    .addComponent(btnCartao)
                    .addComponent(btnPix))
                .addGap(91, 91, 91))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDinheiroActionPerformed
        // TODO add your handling code here:
        String texto = txtValor.getText();//Pega o valor do textField
        double valor = Double.parseDouble(texto);//Converte de string para double e guarda em valor
        PagamentoDinheiro compra1 = new PagamentoDinheiro(valor);//Cria um objeto do tipo PagamentoDinheiro e passa para seu construtor o valor da compra
        compra1.imprimirRecibo();//Chama o metodo imprimirRecibo
        txtValor.setText("");//Limpa o campo valor para a proxima compra
    }//GEN-LAST:event_btnDinheiroActionPerformed

    private void btnCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCartaoActionPerformed
        // TODO add your handling code here:
        String texto = txtValor.getText();//Pega a string do textField
        double valor = Double.parseDouble(texto);//Converte a string para double e guarda na variavel valor da compra
        PagamentoCartao compra2 = new PagamentoCartao(valor);//Cria um objeto do tipo PagamentoCartao e passa para seu construtor o valor da compra
        compra2.imprimirRecibo();//Chama o metodo imprimirRecibo
        txtValor.setText("");//Limpa o campo valor para a proxima compra
    }//GEN-LAST:event_btnCartaoActionPerformed

    private void btnPixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPixActionPerformed
        // TODO add your handling code here:
        String texto = txtValor.getText();//Pega a string do textField
        double valor = Double.parseDouble(texto);//Converte a string em double e guarda em valor
        PagamentoPix compra3 = new PagamentoPix(valor);//Cria um objeto do tipo PagamentoPix e passa para seu construtor o valor da compra
        compra3.imprimirRecibo();//Chama o metodo imprimirRecibo
        txtValor.setText("");//Limpa o campo valor para a proxima compra
    }//GEN-LAST:event_btnPixActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPagamento().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCartao;
    private javax.swing.JButton btnDinheiro;
    private javax.swing.JButton btnPix;
    private javax.swing.JLabel lblPagamento;
    private javax.swing.JLabel lblValor;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
